mysite/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mrmplatform.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls',namespace="polls")),
)

polls/urls.py
from django.conf.urls import patterns, url, include
from django.contrib.auth import authenticate, login
from polls import views

urlpatterns = patterns('',
    url(r'^$',  views.index, {'poll_id':'0'},name='index', ),
    # ex: /polls/5/

    url(r'^questionnaire/$', views.questionnaire, name='questionnaire'),
    
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    # added the word 'specifics'
    url(r'^specifics/(?P<poll_id>\d+)/$', views.detail, name='detail'),

)

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.question
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.choice_text
        
class Userdata(models.Model):
    user_id = models.IntegerField()
    info_type = models.IntegerField()
    info_content = models.CharField(max_length=100)
    info_datetime = models.DateTimeField('input time')
    
    def __unicode__(self):  # Python 3: def __str__(self):
        return self.user_id + info_type + info_content

polls/views.py
#coding=utf-8
#!/usr/bin/python   
from datetime import date, datetime, timedelta, time
from dateutil.relativedelta import relativedelta
from django.utils import timezone

from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate,login,logout


import os, sys
import json
import re
import urllib, urllib2

# 加载数据模型类
from polls.models import Choice, Poll, Userdata
import random

QUESION_NUM = 3

def get_question(poll_id): 
    '''抽题函数，输入为poll的数据库中的id，返回poll对象'''
    try:
        question = Poll.objects.filter(id=int(poll_id))[0]
        return question
    except Exception,e:
        print e
        raise Http404



def index(request, poll_id):
    try:
        latest_poll_list = Poll.objects.all().order_by('-pub_date')[:100] #此处的数字可以限制返回的个数
        question_list = random.sample(latest_poll_list, 3)
        num = len(latest_poll_list)
        print question_list
        poll = question_list[int(poll_id)]
    except Exception,e:
        print e
        raise Http404
    return render(request, 'polls/welcome.html', locals(), context_instance=RequestContext(request))

def questionnaire(request):
    if request.method.upper() == 'POST':
        if 'inputEmail' in request.POST: #只要从注册页面进行的post，自动按照新用户处理！
            if "user_id" in request.session:
                del request.session["user_id"]
            elif "user_progress" in request.session:
                del request.session["user_progress"]
            elif "question_number" in request.session:
                del request.session["question_number"]
            elif "question_id_list" in request.session:
                del request.session["question_id_list"]
        if "user_id" in request.session and "user_progress" in request.session: # 已经拿到系统分配的id
            user_id = request.session["user_id"]
            user_progress = request.session["user_progress"]
            question_max_number = request.session["question_number"]
            question_id_list = request.session["question_id_list"].split(',')
            current_question_id = int(request.POST['question_id'])
            if current_question_id == int(question_id_list[-1]): # 已经答完了最后一道题，跳转到结果页
                #处理结果！。。。
                # 待完善。。。
                #清空用户的session，下次访问算作另一个session
                del request.session["user_id"]
                del request.session["user_progress"]
                del request.session["question_number"] 
                del request.session["question_id_list"]
                # 上面是情况空session的操作
                return render(request, 'polls/result.html', locals(), context_instance=RequestContext(request))
            elif "choice" in request.POST: # 还没答完，记录本题答案，并且展现下一题
                # 获得基本信息
                print 'user_progress',user_progress
                print 'question_id_list[int(user_progress)-1]:', question_id_list[int(user_progress)-1]
                print 'question_id_list[int(user_progress)]:', question_id_list[int(user_progress)]
                if current_question_id == int(question_id_list[int(user_progress)-1]): # 证明用户重复提交，或在页面按了F5，不生成新题,不用保存用户数据！
                    print "F5!"
                    next_question_number = int(question_id_list[int(user_progress)])
                    request.session["user_progress"] = user_progress 
                    poll = get_question(next_question_number)
                    view_progress = 90.0*(user_progress)/(question_max_number) + 10.0 #认为完成注册了就完成了10%
                    return render(request, 'polls/questionnaire.html', locals(), context_instance=RequestContext(request))
                else: # 不是重复提交，保存选择，生成新题
                    user_choice = request.POST['choice'] 
                    question_id_list = request.session["question_id_list"].split(",")
                    current_question_number = int(question_id_list[int(user_progress)])
                    # 保存用户选择
                    UD = Userdata(user_id=user_id, info_type = current_question_number, info_content = user_choice , info_datetime=timezone.now())
                    UD.save()
                    # 生成新的题
                    user_progress = user_progress + 1
                    next_question_number = int(question_id_list[int(user_progress)])
                    request.session["user_progress"] = user_progress
                    poll = get_question(next_question_number)
                    view_progress = 90.0*(user_progress)/(question_max_number) + 10.0 #认为完成注册了就完成了10%
                    print next_question_number,question_max_number
                    return render(request, 'polls/questionnaire.html', locals(), context_instance=RequestContext(request))

                
        else: # 刚刚提交用户注册申请，还没有得到系统生成的user_id
            if 'inputEmail' in request.POST: # 这是正常的情况，else中的情况代表用户在最后一页刷新的情况
                user_email = request.POST['inputEmail'] #后面的空代表默认值
                user_age = request.POST['inputAge']
                user_gender = request.POST['inputGender']
                # 生成一个新的id，先查询数据库中最新的id
                last_id = Userdata.objects.all().order_by('-user_id')[1:1] #此处的数字可以限制返回的个数
                if last_id:
                    user_id = int(last_id[0]) + 1
                else:
                    user_id = 1
                # 将用户录入的信息合并成info_content
                user_info = user_email + '\t' + user_age + '\t' + user_gender
                UD = Userdata(user_id=user_id, info_type = -1, info_content = user_info , info_datetime=timezone.now())
                UD.save()
                #开始抽题
                try:
                    latest_poll_list = Poll.objects.all().order_by('-pub_date')[:100] #此处的数字可以限制返回的个数
                    print 'latest_poll_list:', latest_poll_list
                    question_list = random.sample(latest_poll_list, QUESION_NUM) # 抽3个题
                    print 'question_list:', question_list
                    question_id_list = map(lambda x: str(x.id) , question_list)
                    question_id_list.sort()
                    print 'question_id_list:',question_id_list
                except Exception,e:
                    print e
                    raise Http404
                request.session["user_id"] = user_id
                request.session["user_progress"] = 0
                request.session["question_number"] = QUESION_NUM
                request.session["question_id_list"] = ",".join(question_id_list)
                poll = get_question(question_id_list[0])
                view_progress = 10 #认为完成注册了就完成了10%
                print poll
                return render(request, 'polls/questionnaire.html', locals(), context_instance=RequestContext(request))
            else:
                return HttpResponseRedirect("/polls/")
    elif request.method.upper() == 'GET': # 不是post请求，不予理会，返回主页。
        try:
            latest_poll_list = Poll.objects.all().order_by('-pub_date')[:100] #此处的数字可以限制返回的个数
            question_list = random.sample(latest_poll_list, 3)
            num = len(latest_poll_list)
            print question_list
            poll = question_list[int(poll_id)]
        except Exception,e:
            print e
            raise Http404
        return render(request, 'polls/welcome.html', locals(), context_instance=RequestContext(request))

   
def detail(request, poll_id):
    try:
        poll = Poll.objects.get(pk=poll_id)
        # poll = get_object_or_404(Poll, pk=poll_id)
    except Poll.DoesNotExist:
        raise Http404
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):

    return HttpResponse("You're looking at the results of poll %s." % poll_id)

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

polls/templates/polls/AP_info.html
{% extends "base.html" %}
{% block title %}AP状态信息{% endblock %}

{% block body_main_title %}
<div class="row">

  <div class="col-md-10 col-md-offset-0">
    <h1 class="page-header ">AP状态信息 <small>  </small></h1>
  </div>
</div>
{% endblock body_main_title %}
{% block body_main_content %}
{# 提示信息 #}
{% for note in noti %}
<h5>{{note}}</h5>
{% endfor %}




{# 详细表格 #}
<div id="content-table">
  {% if AP_info_list %}
  <legend>AP_info</legend>
  <table class="table table-striped table-bordered table-condensed tablesorter" id="tablesorter">
    <thead>
      <tr>
        <th>项目</th>
        <th>内容</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
    {% for item in AP_info_list %}
      <tr>
        <td class="name">{{item.name}}</td>
        <td class="value">{{item.value|safe}}</td>
        <td class="action">{{item.action}}</td>
      </tr> 
    {% endfor %}
    </tbody>
  </table>
  <div id="pager" class="pager">
    <div class="row">
      <div class="col-md-2">
        <a class="btn first" href="#"><span class="glyphicon glyphicon-fast-backward"></span></a>
        <a class="btn prev" href="#"><span class="glyphicon glyphicon-backward"></span></a>
      </div>
      <div class="col-md-3">
        <div class="input-group">
        <span class="input-group-addon">每页数量</span>
        <select class="pagesize form-control" >
          <option value="5">5</option>
          <option selected="selected" value="10">10</option>
          <option value="20">20</option>
          <option  value="30">30</option>
          <option  value="50">50</option>
        </select>
        </div>
      </div>
      <div class="col-md-2">
        <div class="input-group">
          <span class="input-group-addon">当前页数</span>
          <input type="text" class="pagedisplay form-control" id="pagedisplay" disabled>
        </div>
      </div>
      <div class="col-md-2">
        <a class="btn next" href="#"><span class="glyphicon glyphicon-forward"></span></a>
        <a class="btn last" href="#"><span class="glyphicon glyphicon-fast-forward"></span></a>
      </div>
    </div>

  </div>
  {% else %}
  {# 提示信息 #}
  {% for note in errors %}
  <h5>{{note}}</h5>
  {% endfor %}
  {% endif %}
</div>


{% endblock body_main_content %}  

{% block body_content_hidden %}


{% endblock body_content_hidden %}




{% block footer_javascript_page %}
<script type="text/javascript">
$(function() {
    $("#tablesorter").tablesorter({widthFixed: true})
    .tablesorterPager({container: $("#pager")});
});
</script>








{% endblock footer_javascript_page %}

polls/templates/polls/chart1.html
{% extends "stat_info_basic.html" %}
{% load staticfiles %}


{% block chart_html %}

<blockquote>

<p>{% if productline %}产品线:<span class="label label-success">{{productline}}</span> || {% endif %}
{% if adder %}创建者:<span class="label label-success">{{adder}}</span> || {% endif %}
{% if status %}状态:<span class="label label-success">{{status}}</span> || {% endif %}
from:<span class="label label-info">{{chart_show_fromtime}}</span>
to:<span class="label label-info">{{chart_show_totime}}</span>
</p>
</blockquote>
{% ifequal chart_status 'success' %}
<div id="main" style="min-width:700px;height:400px"></div>
{% endifequal %}
{% endblock chart_html %}


{% block chart_js %}
{% ifequal chart_status 'success' %}
<script type="text/javascript">
$(function () {
    $('#main').highcharts({
        chart: {
            zoomType: 'x',
            spacingRight: 20
        },
        title: {
            text: '任务申请情况统计图(天级)'
        },
        subtitle: {
            text: document.ontouchstart === undefined ?
                '选取区域可放大' :
                'Pinch the chart to zoom in'
        },
        xAxis: {
            type: 'datetime',
            maxZoom: 5 * 24 * 3600000, // fourteen days
            title: {
                text: 'Date range'
            }
        },
        yAxis: {
            title: {
                text: 'Numbers of creat jobs'
            }
        },
        tooltip: {
            shared: true
        },
        legend: {
            enabled: false
        },
        plotOptions: {
            area: {
                fillColor: {
                    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
                    stops: [
                        [0, Highcharts.getOptions().colors[0]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                    ]
                },
                lineWidth: 1,
                marker: {
                    enabled: false
                },
                shadow: false,
                states: {
                    hover: {
                        lineWidth: 1
                    }
                },
                threshold: null
            }
        },

        series: [{
            type: 'area',
            name: 'job numbers',
            pointInterval: 24 * 3600 * 1000,
            pointStart: Date.UTC({{chart1_year}}, {{chart1_month}}, {{chart1_day}}),
            data: [
            {% for value in statistic1_dict_num %}
            {{value}}, 
          {% endfor %}
            ]
        }]
    });
});       
</script>
{% endifequal%}
{% endblock chart_js %}

polls/templates/polls/chart2.html
{% extends "stat_info_basic.html" %}
{% load staticfiles %}
{% block title %}统计信息{% endblock %}





{% block chart_html %}
{# chart 2 #}
<blockquote>
<p>{% if productline %}产品线:<span class="label label-success">{{productline}}</span> || {% endif %}
{% if adder %}创建者:<span class="label label-success">{{adder}}</span> || {% endif %}
{% if status %}状态:<span class="label label-success">{% ifequal status '0' %}无效{% endifequal %}
                {% ifequal status '1' %}排队{% endifequal %}
                {% ifequal status '2' %}运行中{% endifequal %}
                {% ifequal status '3' %}结束{% endifequal %}
                {% ifequal status '4' %}用户停止{% endifequal %}</span> || {% endif %}
from:<span class="label label-info">{{chart_show_fromtime}}</span>
to:<span class="label label-info">{{chart_show_totime}}</span>
</p>
</blockquote>

{% ifequal chart_status 'success'%}
<blockquote>
<div id="main" style="height:400px"></div>
</blockquote>
{% endifequal %}

{% endblock chart_html %}

{% block chart_js %}

{% ifequal chart_status 'success'%}
<script src="{% static "require.js" %}" ></script>
<script >
require.config({
  packages: [
      {
          name: 'echarts',
          location: '{% static "echarts-1.3.7/src" %}',      
          main: 'echarts'
      },
      {
          name: 'zrender',
          location: '{% static "zrender-1.0.9/src"%}', 
          main: 'zrender'
      }
  ]
});


var option = {
    title : {
        text: 'job状态统计图',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:['无效','排队','运行中','结束','用户停止']
    },
    toolbox: {
        show : true,
        feature : {
            mark : true,
            dataView : {readOnly: false},
            restore : true,
            saveAsImage : true
        }
    },
    calculable : true,
    series : [
        {
            name:'状态',
            type:'pie',
            radius : [0, 110],
            center: ['40%', 225],
            data:[
                {value:{{statistic2_dict.0}}, name:'无效'},
                {value:{{statistic2_dict.1}}, name:'排队'},
                {value:{{statistic2_dict.2}}, name:'运行中'},
                {value:{{statistic2_dict.3}}, name:'结束'},
                {value:{{statistic2_dict.4}}, name:'用户停止'}
            ]
        }
    ]
};
       

require(
    [
        'echarts',
        'echarts/chart/line',
        'echarts/chart/bar',
        'echarts/chart/pie'
    ],
    function(ec) {
        var myChart = ec.init(document.getElementById('main'));
        myChart.setOption(option);
    }
)
{% endifequal %}

</script>

{% endblock chart_js %}

polls/templates/polls/chart3.html
{% extends "stat_info_basic.html" %}
{% load staticfiles %}
{% block title %}统计信息{% endblock %}





{% block chart_html %}
{# chart 3 #}
<blockquote>
<p>{% if productline %}产品线:<span class="label label-success">{{productline}}</span> || {% endif %}
{% if adder %}创建者:<span class="label label-success">{{adder}}</span> || {% endif %}
{% if status %}状态:<span class="label label-success">
                {% ifequal status '0' %}无效{% endifequal %}
                {% ifequal status '1' %}排队{% endifequal %}
                {% ifequal status '2' %}运行中{% endifequal %}
                {% ifequal status '3' %}结束{% endifequal %}
                {% ifequal status '4' %}用户停止{% endifequal %}</span>
 || {% endif %}
from:<span class="label label-info">{{chart_show_fromtime}}</span>
to:<span class="label label-info">{{chart_show_totime}}</span>
</p>
</blockquote>

{% if job_time_statistic_dict %}
<blockquote>
  <table class="table">
    <thead>
      <tr>
        <th>项目</th>
        <th>内容</th>
        <th>有效统计的job数量</th>
      </tr>
    </thead>
    <tbody>
      <tr class="success">
        <td>任务平均使用时间</td>
        <td>{{job_time_statistic_dict.avg_use_time}}</td>
        <td>{{job_time_statistic_dict.job_success_statistic_num}}</td>
      </tr>
      <tr class="success">
        <td>任务平均排队时间</td>
        <td>{{job_time_statistic_dict.avg_queue_time}}</td>
        <td>{{job_time_statistic_dict.job_success_statistic_num}}</td>
      </tr>
      <tr class="error">
        <td>时间信息不全的任务数量</td>
        <td>------</td>
        <td>{{job_time_statistic_dict.job_failed_statistic_num}}</td>
      </tr>
    </tbody>
  </table>
</blockquote>
{% endif %}

{% endblock chart_html %}

{% block chart_js %}

{% ifequal chart_status 'success'%}
<script src="{% static "require.js" %}" ></script>
<script >
require.config({
  packages: [
      {
          name: 'echarts',
          location: '{% static "echarts-1.3.7/src" %}',      
          main: 'echarts'
      },
      {
          name: 'zrender',
          location: '{% static "zrender-1.0.9/src"%}', 
          main: 'zrender'
      }
  ]
});


var option = {
    title : {
        text: 'job状态统计图',
        subtext: '',
        x:'center'
    },
    tooltip : {
        trigger: 'item',
        formatter: "{a} <br/>{b} : {c} ({d}%)"
    },
    legend: {
        orient : 'vertical',
        x : 'left',
        data:['无效','排队','运行中','结束','用户停止']
    },
    toolbox: {
        show : true,
        feature : {
            mark : true,
            dataView : {readOnly: false},
            restore : true,
            saveAsImage : true
        }
    },
    calculable : true,
    series : [
        {
            name:'状态',
            type:'pie',
            radius : [0, 110],
            center: ['40%', 225],
            data:[
                {value:{{statistic2_dict.0}}, name:'无效'},
                {value:{{statistic2_dict.1}}, name:'排队'},
                {value:{{statistic2_dict.2}}, name:'运行中'},
                {value:{{statistic2_dict.3}}, name:'结束'},
                {value:{{statistic2_dict.4}}, name:'用户停止'}
            ]
        }
    ]
};
       

require(
    [
        'echarts',
        'echarts/chart/line',
        'echarts/chart/bar',
        'echarts/chart/pie'
    ],
    function(ec) {
        var myChart = ec.init(document.getElementById('main'));
        myChart.setOption(option);
    }
)
{% endifequal %}

</script>

{% endblock chart_js %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block title %}Welcome to SDNController+!{% endblock %}


{% block body_main_content %}
<div class="span10">
	<div class="panel-group" id="accordion1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <a data-toggle="collapse" data-parent="#accordion1" href="#collapseOne"><h5>欢迎</h5></a>
      </div>
      <div id="collapseOne" class="panel-collapse collapse in">
        <div class="panel-body">
					<p>{{ poll.id }}  {{ poll.question }}  {{ poll.question }}</p> 
					<form action="{% url 'polls:vote' poll.id %}" method="post">
          {% csrf_token %}
          {% for choice in poll.choice_set.all %}
              <input type="radio" name="choice"  id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
              <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
          {% endfor %}
          <input type="submit" value="Vote" />
          </form>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
      	<a data-toggle="collapse" data-parent="#accordion1" href="#collapseTwo"><h5>DEMO</h5></a>
      </div>
      <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-body">
					<iframe src="https://www.google.com/" frameborder="0" seamless="seamless" scrolling="auto" style="height:518px;width:1185px;"></iframe>
        </div>
      </div>
    </div>
    <div class="panel panel-default" >
      <div class="panel-heading">
        <a data-toggle="collapse" data-parent="#accordion1" href="#collapseThree"><h5>功能说明</h5></a>
      </div>
    	<div id="collapseThree" class="panel-collapse collapse">
      	<div class="panel-body">
      		<div id="chart1" style="min-width:1000px;height:300px"></div>
      		<div id="chart2" style="min-width:1000px;height:300px"></div>
       	</div>
      </div>
    </div>
  </div>
</div>
{% endblock body_main_content %}  
	  

{% block footer_javascript_page %}




<script>
$(document).ready(function(){
  $("input").click(function(){
   var id = $("input").attr("id");


    $("form").submit();


  });
});
</script>
{% endblock footer_javascript_page %}

polls/templates/polls/login.html
{% extends "base.html" %}

{% load i18n admin_static %}

{% block head_title %}LOG IN{% endblock head_title %}
{% block body_main %}



<div class="row-fluid">
  <div class="span4 offset4">
    <h2 class="page-header">用户认证</h2>

      <div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><strong>用户名或密码不正确</strong></p> 
      <p>{% for error in errors %}{{ error }}{% endfor %}</p>
      </div>


    <form class="form-horizontal" action="{{ app_path }}" method="post">
      {%csrf_token%}
      <div class="control-group">
        <label class="control-label" for="username">用户名</label>
        <div class="controls">
          <input id="username" name="username" type="text" placehoder="请输入用户名">
          {% if not form.this_is_the_login_form.errors %}<p class="help-block">{{ form.username.errors }}</p>{% endif %}
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="password">密码</label>
        <div class="controls">
          <input id="password" name="password" type="password" placehoder="请输入密码">
          {% if not form.this_is_the_login_form.errors %}<p class="help-block">{{ form.password.errors }}</p>{% endif %}
        </div>
      </div>
      {% url 'admin_password_reset' as password_reset_url %}
      {% if password_reset_url %}
      <div class="password-reset-link">
        <a href="{{ password_reset_url }}">{% trans 'Forgotten your password or username?' %}</a>
      </div>
      {% endif %}
      <div class="form-actions">
        <button type="submit" class="btn btn-primary">登录</button>
        <input type="hidden" name="next" value="{{ next|escape }}" />
      </div>
    </form>
  </div>
</div>






{% endblock body_main %}

polls/templates/polls/request_failed.html
{% extends "base.html" %}
{% block title %}Something Wrong happends!{% endblock %}


{% block body_main_content %}
                

	  	<div class="hero-unit">
			  <h1><p class="text-error">{{ error_title }}</p></h1>
			  <p></p>
			  {% for error in errors %}<p>{{ error }}</p>{% endfor %}
			  <p>
			    <a class="btn btn-primary btn-large" href="/">
			      &larr;返回首页
			    </a>
			  </p>
			</div>
{% endblock body_main_content %} 

polls/templates/polls/result.html
{% extends "base.html" %}
{% block title %}Welcome to SDNController+!{% endblock %}


{% block body %}
<body class="container default-bg">
<div class="container">

  <div class="jumbotron">
    <h1>感谢您的参与!</h1>
    <p>您已经完成所有的题目。您抽到的题目编号是：{{question_id_list}}</p>
    <p><a href="/polls/" class="btn btn-primary btn-lg" role="button">重新开始</a></p>
  </div>

</div>
</body>
{% endblock body %}  
	  

{% block footer_javascript_page %}




<script>
function IsMatchingAddress(str){
    var myRegExp = /[a-z0-9-]{1,30}@[a-z0-9-]{1,65}.[a-z]+/ ;
    return myRegExp.test(str);
}
function IsMatchingAge(str){
    var myRegExp = /^[0-9-]+$/ ;
    return myRegExp.test(str) && str.length <=2;
}
function IsNotEmpty(str){
    if(str){
    var length = str.replace(/(^\s+)|(\s+$)/g, "").length;
    return length !== 0;
    }
    else{ return false;}
}



$(document).ready(function(){
  $("#button_begin").click(function(){
    var check_ok=false;
    if (IsMatchingAddress($("#inputEmail").val()) && IsMatchingAge($("#inputAge").val()) && $('input[name="inputGender"]:checked').val() )
      {
          alert("ok");
          $("#form_user_info").submit();
      }
    else
      {
      $("#err_msg").html("请填写正确的信息后继续~");
      }
  });
});

</script>
{% endblock footer_javascript_page %}